### ISSUE TITLE
앞으로 사용할 README 템플릿 양식 논의

### ISSUE THREAD

**Issue by yoopark** [pre-onboarding-frontend-11th-team-9/pre-onboarding-11th-1-9#10]
저도 한번 만들어보고 있었는데 이미 만드셨더라구요 ㅎㅎ
잠깐 논의해서 스타일 합치면 될 것 같습니다. 

https://github.com/pre-onboarding-frontend-11th-team-9/.github/blob/main/README_TEMPLATE.md

**Comment by rockbell89** [comment]
좋습니다!!

**Comment by yoopark** [comment]
- #11
